"""initial schema: jobs, compares

Revision ID: 0001
Revises:
Create Date: 2026-08-29

Hand-written, not autogenerated — mirrors app/db/models.py exactly. Keep the
two in sync by hand; there is no live DB in this environment to diff against.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

JOB_STATUSES = ("queued", "processing", "completed", "failed")
JOB_STAGES = (
    "loading_input",
    "estimating_depth",
    "fetching_reference",
    "calibrating",
    "packaging",
    "validating_output",
    "uploading_results",
)
COMPARE_STAGES = ("loading_inputs", "aligning", "computing_diff", "packaging", "uploading_results")
OUTPUT_TYPES = ("relative_dsm", "absolute_dsm")


def upgrade() -> None:
    op.create_table(
        "jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="queued"),
        sa.Column("stage", sa.String(32), nullable=True),
        sa.Column("progress", sa.Integer, nullable=False, server_default="0"),
        sa.Column("input_path", sa.Text, nullable=False),
        sa.Column("input_filename", sa.Text, nullable=False),
        sa.Column("input_media_type", sa.String(64), nullable=False),
        sa.Column("output_type", sa.String(16), nullable=True),
        sa.Column("texture_path", sa.Text, nullable=True),
        sa.Column("heightmap_path", sa.Text, nullable=True),
        sa.Column("heightmap_16bit_path", sa.Text, nullable=True),
        sa.Column("confidence_map_path", sa.Text, nullable=True),
        sa.Column("dsm_path", sa.Text, nullable=True),
        sa.Column("metadata_path", sa.Text, nullable=True),
        sa.Column("metadata", postgresql.JSONB, nullable=True),
        sa.Column("metrics", postgresql.JSONB, nullable=True),
        sa.Column("warnings", postgresql.ARRAY(sa.Text), nullable=False, server_default="{}"),
        sa.Column("error_code", sa.String(64), nullable=True),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("celery_task_id", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(f"status IN {JOB_STATUSES}", name="jobs_status_valid"),
        sa.CheckConstraint(f"stage IS NULL OR stage IN {JOB_STAGES}", name="jobs_stage_valid"),
        sa.CheckConstraint("progress >= 0 AND progress <= 100", name="jobs_progress_range"),
        sa.CheckConstraint(f"output_type IS NULL OR output_type IN {OUTPUT_TYPES}", name="jobs_output_type_valid"),
    )
    op.create_index("ix_jobs_user_id_created_at", "jobs", ["user_id", "created_at"])

    op.create_table(
        "compares",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "before_job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "after_job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("status", sa.String(16), nullable=False, server_default="queued"),
        sa.Column("stage", sa.String(32), nullable=True),
        sa.Column("progress", sa.Integer, nullable=False, server_default="0"),
        sa.Column("diff_map_path", sa.Text, nullable=True),
        sa.Column("before_texture_path", sa.Text, nullable=True),
        sa.Column("after_texture_path", sa.Text, nullable=True),
        sa.Column("metadata", postgresql.JSONB, nullable=True),
        sa.Column("warnings", postgresql.ARRAY(sa.Text), nullable=False, server_default="{}"),
        sa.Column("error_code", sa.String(64), nullable=True),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("celery_task_id", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(f"status IN {JOB_STATUSES}", name="compares_status_valid"),
        sa.CheckConstraint(f"stage IS NULL OR stage IN {COMPARE_STAGES}", name="compares_stage_valid"),
        sa.CheckConstraint("progress >= 0 AND progress <= 100", name="compares_progress_range"),
    )
    op.create_index("ix_compares_user_id_created_at", "compares", ["user_id", "created_at"])


def downgrade() -> None:
    op.drop_table("compares")
    op.drop_table("jobs")
