"""silt_jobs table (river-silt use case)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-14

Hand-written, not autogenerated — mirrors app/db/models.py's SiltJob exactly,
same convention as 0001_initial.py.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None

JOB_STATUSES = ("queued", "processing", "completed", "failed")
SILT_JOB_STAGES = ("loading_input", "estimating_silt", "packaging", "uploading_results")
SILT_OUTPUT_TYPES = ("relative_silt_index", "absolute_ssc")


def upgrade() -> None:
    op.create_table(
        "silt_jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="queued"),
        sa.Column("stage", sa.String(32), nullable=True),
        sa.Column("progress", sa.Integer, nullable=False, server_default="0"),
        sa.Column("input_path", sa.Text, nullable=False),
        sa.Column("input_filename", sa.Text, nullable=False),
        sa.Column("input_media_type", sa.String(64), nullable=False),
        sa.Column("output_type", sa.String(32), nullable=True),
        sa.Column("texture_path", sa.Text, nullable=True),
        sa.Column("heatmap_path", sa.Text, nullable=True),
        sa.Column("predicted_ssc_mg_l", sa.Float, nullable=True),
        sa.Column("metadata", postgresql.JSONB, nullable=True),
        sa.Column("warnings", postgresql.ARRAY(sa.Text), nullable=False, server_default="{}"),
        sa.Column("error_code", sa.String(64), nullable=True),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("celery_task_id", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(f"status IN {JOB_STATUSES}", name="silt_jobs_status_valid"),
        sa.CheckConstraint(f"stage IS NULL OR stage IN {SILT_JOB_STAGES}", name="silt_jobs_stage_valid"),
        sa.CheckConstraint("progress >= 0 AND progress <= 100", name="silt_jobs_progress_range"),
        sa.CheckConstraint(
            f"output_type IS NULL OR output_type IN {SILT_OUTPUT_TYPES}", name="silt_jobs_output_type_valid"
        ),
    )
    op.create_index("ix_silt_jobs_user_id_created_at", "silt_jobs", ["user_id", "created_at"])


def downgrade() -> None:
    op.drop_table("silt_jobs")
